// Code generated by smithy-go-codegen DO NOT EDIT.

package s3

import (
	"context"
	"errors"
	"io/ioutil"
	"net"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	awshttp "github.com/aws/aws-sdk-go-v2/aws/transport/http"
	awsrdmahttp "github.com/aws/aws-sdk-go-v2/aws/transport/http/rdma"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func TestClient_resolveRetryOptions(t *testing.T) {
	nopClient := smithyhttp.ClientDoFunc(func(_ *http.Request) (*http.Response, error) {
		return &http.Response{
			StatusCode: 200,
			Header:     http.Header{},
			Body:       ioutil.NopCloser(strings.NewReader("")),
		}, nil
	})

	cases := map[string]struct {
		defaultsMode            aws.DefaultsMode
		retryer                 aws.Retryer
		retryMaxAttempts        int
		opRetryMaxAttempts      *int
		retryMode               aws.RetryMode
		expectClientRetryMode   aws.RetryMode
		expectClientMaxAttempts int
		expectOpMaxAttempts     int
	}{
		"defaults": {
			defaultsMode:            aws.DefaultsModeStandard,
			expectClientRetryMode:   aws.RetryModeStandard,
			expectClientMaxAttempts: 3,
			expectOpMaxAttempts:     3,
		},
		"custom default retry": {
			retryMode:               aws.RetryModeAdaptive,
			retryMaxAttempts:        10,
			expectClientRetryMode:   aws.RetryModeAdaptive,
			expectClientMaxAttempts: 10,
			expectOpMaxAttempts:     10,
		},
		"custom op max attempts": {
			retryMode:               aws.RetryModeAdaptive,
			retryMaxAttempts:        10,
			opRetryMaxAttempts:      aws.Int(2),
			expectClientRetryMode:   aws.RetryModeAdaptive,
			expectClientMaxAttempts: 10,
			expectOpMaxAttempts:     2,
		},
		"custom op no change max attempts": {
			retryMode:               aws.RetryModeAdaptive,
			retryMaxAttempts:        10,
			opRetryMaxAttempts:      aws.Int(10),
			expectClientRetryMode:   aws.RetryModeAdaptive,
			expectClientMaxAttempts: 10,
			expectOpMaxAttempts:     10,
		},
		"custom op 0 max attempts": {
			retryMode:               aws.RetryModeAdaptive,
			retryMaxAttempts:        10,
			opRetryMaxAttempts:      aws.Int(0),
			expectClientRetryMode:   aws.RetryModeAdaptive,
			expectClientMaxAttempts: 10,
			expectOpMaxAttempts:     10,
		},
	}

	for name, c := range cases {
		t.Run(name, func(t *testing.T) {
			client := NewFromConfig(aws.Config{
				DefaultsMode: c.defaultsMode,
				Retryer: func() func() aws.Retryer {
					if c.retryer == nil {
						return nil
					}

					return func() aws.Retryer { return c.retryer }
				}(),
				HTTPClient:       nopClient,
				RetryMaxAttempts: c.retryMaxAttempts,
				RetryMode:        c.retryMode,
			}, func(o *Options) {
				if o.Retryer == nil {
					t.Errorf("retryer must not be nil in functional options")
				}
			})

			if e, a := c.expectClientRetryMode, client.options.RetryMode; e != a {
				t.Errorf("expect %v retry mode, got %v", e, a)
			}
			if e, a := c.expectClientMaxAttempts, client.options.Retryer.MaxAttempts(); e != a {
				t.Errorf("expect %v max attempts, got %v", e, a)
			}

			_, _, err := client.invokeOperation(context.Background(), "mockOperation", struct{}{},
				[]func(*Options){
					func(o *Options) {
						if c.opRetryMaxAttempts == nil {
							return
						}
						o.RetryMaxAttempts = *c.opRetryMaxAttempts
					},
				},
				func(s *middleware.Stack, o Options) error {
					s.Initialize.Clear()
					s.Serialize.Clear()
					s.Build.Clear()
					s.Finalize.Clear()
					s.Deserialize.Clear()

					if e, a := c.expectOpMaxAttempts, o.Retryer.MaxAttempts(); e != a {
						t.Errorf("expect %v op max attempts, got %v", e, a)
					}
					return nil
				})
			if err != nil {
				t.Fatalf("expect no operation error, got %v", err)
			}
		})
	}
}

func TestClient_resolveHTTPClient_RDMATransportFallback(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	var openCalled int32
	var fallbackCalled int32

	client := New(Options{
		Region:              "us-west-2",
		EnableRDMATransport: true,
		HTTPClient: awshttp.NewBuildableClient().WithTransportOptions(func(tr *http.Transport) {
			tr.Proxy = nil
		}),
		RDMADialer: awsrdmahttp.Dialer{
			Open: func(ctx context.Context, network, address string) (awsrdmahttp.MessageConn, error) {
				atomic.AddInt32(&openCalled, 1)
				return nil, errors.New("rdma unavailable")
			},
			FallbackDialContext: func(ctx context.Context, network, address string) (net.Conn, error) {
				atomic.AddInt32(&fallbackCalled, 1)
				return (&net.Dialer{}).DialContext(ctx, network, address)
			},
		},
	})

	buildable := client.options.HTTPClient.(*awshttp.BuildableClient)
	req, _ := http.NewRequest("GET", srv.URL, nil)
	resp, err := buildable.Do(req)
	if err != nil {
		t.Fatalf("expect no error, got %v", err)
	}
	defer resp.Body.Close()

	if e, a := http.StatusOK, resp.StatusCode; e != a {
		t.Fatalf("expect status %v, got %v", e, a)
	}

	if atomic.LoadInt32(&openCalled) == 0 {
		t.Fatalf("expected RDMA Open to be called")
	}
	if atomic.LoadInt32(&fallbackCalled) == 0 {
		t.Fatalf("expected fallback dial to be called")
	}
}

func TestClient_resolveHTTPClient_RDMATransportDisableFallback(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	var openCalled int32
	var fallbackCalled int32

	client := New(Options{
		Region:              "us-west-2",
		EnableRDMATransport: true,
		HTTPClient: awshttp.NewBuildableClient().WithTransportOptions(func(tr *http.Transport) {
			tr.Proxy = nil
		}),
		RDMADialer: awsrdmahttp.Dialer{
			DisableFallback: true,
			Open: func(ctx context.Context, network, address string) (awsrdmahttp.MessageConn, error) {
				atomic.AddInt32(&openCalled, 1)
				return nil, errors.New("rdma disabled")
			},
			FallbackDialContext: func(ctx context.Context, network, address string) (net.Conn, error) {
				atomic.AddInt32(&fallbackCalled, 1)
				return (&net.Dialer{}).DialContext(ctx, network, address)
			},
		},
	})

	buildable := client.options.HTTPClient.(*awshttp.BuildableClient)
	req, _ := http.NewRequest("GET", srv.URL, nil)
	_, err := buildable.Do(req)
	if err == nil {
		t.Fatalf("expected dial error")
	}

	if atomic.LoadInt32(&openCalled) == 0 {
		t.Fatalf("expected RDMA Open to be called")
	}
	if atomic.LoadInt32(&fallbackCalled) != 0 {
		t.Fatalf("expected fallback dial not to be called")
	}
}

func TestClient_resolveHTTPClient_RDMATransportEnabledByEnv(t *testing.T) {
	t.Setenv(awsS3EnableRDMATransportEnv, "true")

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	var fallbackCalled int32

	client := New(Options{
		Region: "us-west-2",
		HTTPClient: awshttp.NewBuildableClient().WithTransportOptions(func(tr *http.Transport) {
			tr.Proxy = nil
		}),
		RDMADialer: awsrdmahttp.Dialer{
			FallbackDialContext: func(ctx context.Context, network, address string) (net.Conn, error) {
				atomic.AddInt32(&fallbackCalled, 1)
				return (&net.Dialer{}).DialContext(ctx, network, address)
			},
		},
	})

	buildable := client.options.HTTPClient.(*awshttp.BuildableClient)
	req, _ := http.NewRequest("GET", srv.URL, nil)
	resp, err := buildable.Do(req)
	if err != nil {
		t.Fatalf("expect no error, got %v", err)
	}
	defer resp.Body.Close()

	if atomic.LoadInt32(&fallbackCalled) == 0 {
		t.Fatalf("expected fallback dial to be called when env enables RDMA transport")
	}
}

func TestClient_resolveHTTPClient_RDMATransportDisabledByEnv(t *testing.T) {
	t.Setenv(awsS3EnableRDMATransportEnv, "false")

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	var openCalled int32

	client := New(Options{
		Region:              "us-west-2",
		EnableRDMATransport: true,
		HTTPClient: awshttp.NewBuildableClient().WithTransportOptions(func(tr *http.Transport) {
			tr.Proxy = nil
		}),
		RDMADialer: awsrdmahttp.Dialer{
			DisableFallback: true,
			Open: func(ctx context.Context, network, address string) (awsrdmahttp.MessageConn, error) {
				atomic.AddInt32(&openCalled, 1)
				return nil, errors.New("rdma should be disabled by env")
			},
		},
	})

	buildable := client.options.HTTPClient.(*awshttp.BuildableClient)
	req, _ := http.NewRequest("GET", srv.URL, nil)
	resp, err := buildable.Do(req)
	if err != nil {
		t.Fatalf("expect no error, got %v", err)
	}
	defer resp.Body.Close()

	if atomic.LoadInt32(&openCalled) != 0 {
		t.Fatalf("expected RDMA Open not to be called when env disables RDMA transport")
	}
}
